image: usvc/ci-golang:gitlab-latest
services:
  - docker:dind
stages:
  - validation
  - versioning
  - release
  - publish
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# run tests:
#   stage: validation
#   artifacts:
#     untracked: false
#     expire_in: 3 days
#     paths:
#       - ./c.out
#   script:
#     - make dep
#     - make test

# build binary:
#   stage: validation
#   artifacts:
#     untracked: false
#     expire_in: 3 days
#     paths:
#       - ./bin/semver
#   script:
#     - make dep
#     - make binaries

# build images:
#   stage: validation
#   script:
#     - make images

bump:
  stage: versioning
  script:
    - git remote set-url origin "${GITLAB_DEPLOY_URL}"
    - git checkout master
    - git tag --list
    - docker run -v $(pwd):/repo usvc/semver:latest + --git --apply
    - git tag --list
    - 'printf -- "${GITLAB_DEPLOY_KEY}" > ~/id_rsa'
    - git branch
    - git push --tags
    - 'printf -- "placeholder - bump the version here and push the tag back to gitlab"'

docker image:
  only: ["tags"]
  stage: release
  script:
    - docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
    - make publish_images
    - docker logout

to github:
  only: ["tags"]
  stage: publish
  script:
    - 'printf -- "placeholder - push the repo to github at this stage"'
