image: usvc/ci-golang:gitlab-latest
services:
  - docker:dind
stages:
  - validation
  - release
variables:
  GIT_SUBMODULE_STRATEGY: recursive

run tests:
  stage: validation
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - ./c.out
  script:
    - make dep
    - make test

build binary:
  stage: validation
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - ./bin/semver
  script:
    - make dep
    - make binaries

build images:
  stage: validation
  script:
    - make images

docker image:
  stage: release
  script:
    - docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
    - make publish_image
    - docker logout
