image: usvc/ci-golang:gitlab-latest
services:
  - docker:dind
stages:
  - validation
  - versioning
  - release
  - validate_release
  - publish
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# run tests:
#   # only: ["master"]
#   stage: validation
#   artifacts:
#     untracked: false
#     expire_in: 3 days
#     paths:
#       - ./c.out
#   script:
#     - make dep
#     - make test

# build binary:
#   # only: ["master"]
#   stage: validation
#   artifacts:
#     untracked: false
#     expire_in: 3 days
#     paths:
#       - ./bin/semver
#   script:
#     - make dep
#     - make binaries

# build images:
#   # only: ["master"]
#   stage: validation
#   script:
#     - make images

# bump:
#   # only: ["master"]
#   stage: versioning
#   image: usvc/semver:gitlab-latest
#   before_script:
#     - mkdir -p ~/.ssh
#     - 'printf -- "${GITLAB_DEPLOY_KEY}" | base64 -d > ~/.ssh/id_rsa'
#     - chmod 600 -R ~/.ssh/id_rsa
#     - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
#   script:
#     - git remote set-url origin "${GITLAB_DEPLOY_URL}"
#     - git checkout master
#     - semver bump --git --apply
#     - git push origin master --verbose --tags
#   after_script:
#     - rm -rf ~/.ssh/*

# docker image:
#   # only: ["tags"]
#   stage: release
#   script:
#     - docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
#     - make publish_images
#     - docker logout

to github:
  # only: ["tags"]
  stage: publish
  before_script:
    - mkdir -p ~/.ssh
    - 'printf -- "${GITHUB_DEPLOY_KEY}" | base64 -d > ~/.ssh/id_rsa'
    - chmod 600 -R ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - git config --global user.email "usvc.semver@usvc.dev"
    - git config --global user.name "usvc_publisher"
    - make publish_github
    - 'printf -- "placeholder - push the repo to github at this stage"'
  after_script:
    - rm -rf ~/.ssh/*
