stages:
  - validation
  - release

run tests:
  stage: validation
  image: golang:1.12.4-alpine
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - ./c.out
  before_script:
    - apk add --no-cache make git gcc g++
  script:
    - make dep
    - make test

build binary:
  stage: validation
  image: golang:1.12.4-alpine
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - ./bin/semver
  before_script:
    - apk add --no-cache make git gcc g++
  script:
    - make dep
    - make build

docker image:
  services:
    - docker:dind
  stage: release
  image: usvc/ci-docker:latest
  script:
    - docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
    - make publish_image
    - docker logout
