name: Go Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""
          - os: windows
            arch: 386
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git g++ upx gcc-arm-linux* g++-arm-linux*

      - name: Make Dependencies
        run: make deps

      - name: Build Production
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} BIN_EXT=${{ matrix.ext }} make build_production

      - name: Compress
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} BIN_EXT=${{ matrix.ext }} make compress || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ./bin/*

  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - name: Install Dependencies
        run: brew install make git upx

      - name: Make Dependencies
        run: make deps

      - name: Build Production
        run: GOOS=darwin GOARCH=${{ matrix.arch }} make build_production

#      - name: Compress
#        run: GOOS=darwin GOARCH=${{ matrix.arch }} make compress || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: darwin-${{ matrix.arch }}
          path: ./bin/*

  bump-version:
    runs-on: ubuntu-latest
    needs: [build-linux-windows, build-darwin]
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

  release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump_version.outputs.new_tag }}
          name: Release ${{ needs.bump_version.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            ./bin/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
